### PR TITLE
Add App.config custom config section storage

### PR DESCRIPTION
**Pull request by kneefer**
Not sure if it should be added as optional parameter to existing `UseAppConfig` extension method. Decided to create separate `UseAppConfigSection(string sectionName)` to make it more explicit. Documentation with sample usage is also provided. 

Let me know if you want tests for this functionality. Also I will understand if you recognize this PR useless - we use this store in several of our applications so decided to share it :)

### CODE REVIEW

**Comment by aloneguid** [comment]
It looks good actually, really useful. Is there any chance you can add a unit test or two so it's not broken by anyone in future? Thanks for contributing!

**Comment by kneefer** [comment]
Thank you! No problem, probably I will find some time to write them even today.

**Comment by aloneguid** [comment]
@kneefer did you have a chance to look at it? ;)

**Comment by aloneguid** [comment]
closing this as it's 6 month old.

**Pull request closed without merging**
