### PR TITLE
Add support of DefaultValueAttribute

### LINKED ISSUE #98: Support of DefaultValueAttribute
Hello,

Would it be possible to support  System.ComponentModel.DefaultValueAttribute additionally to OptionAttribute(DefaultValue= )?
In my case I don't want to propagate Config.net in all my code (for instances some plugins), and that would be a good solution.

Thanks,
Laurent

### PR DESCRIPTION
**Pull request by LaurentMinot**
Closes #98 
Add support of standard [DefaultValue] attribute

### CODE REVIEW

**Comment by LaurentMinot** [comment]
(failing tests are Azure one, I think it's ore a matter of configuration than somethig I broke)

**Comment by aloneguid** [comment]
Thanks, tests are relying on some Azure resources that do not exist anymore. I'll have to disable those for now.

**Comment by aloneguid** [comment]
Just updated readme, let me know if you're happy with this.

**Comment by LaurentMinot** [comment]
Perfect

**Pull request merged**
